apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: mongodb-sink-connector
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: com.mongodb.kafka.connect.MongoSinkConnector
  tasksMax: 2
  config:
    topics: mongo.kafkamongodb.kafkamongodbcollection
    connection.uri: mongodb://kafkamongodbaccount:TFpok5LqZOUeYX0SnEU0HInXL1J7tfOXvFqfLB1N2M5vaS7osyMXSYBnh3wwt2nRmsVSt0KHlSiMdUnqwPyAgw==@kafkamongodbaccount.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@kafkamongodbaccount@
    database: kafkamongosinkdb
    collection: kafkamongosinkdbcollection
    post.processor.chain: com.mongodb.kafka.connect.sink.processor.DocumentIdAdder,com.mongodb.kafka.connect.sink.processor.KafkaMetaAdder
    key.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
